-- CSAT Dashboard SQL Queries
-- Database: SANDBOX_LAKEHOUSE (EU)
-- Schema: INTERNAL_ANALYTICS
-- Table: ZENDESK_PRODUCTIVITY_METRICS_TICKETS

-- =====================================================
-- 1. OVERALL CSAT METRICS (Current Month)
-- =====================================================
SELECT
  DATE_TRUNC('MONTH', TICKET_CREATION_TIME) AS MONTH,
  COUNT(*) AS TOTAL_TICKETS,
  SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS RATED_TICKETS,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS RESPONSE_RATE_PCT,
  COUNT(DISTINCT CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN TICKET_ID END) AS SATISFIED_TICKETS,
  ROUND(100.0 * COUNT(DISTINCT CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN TICKET_ID END) / NULLIF(SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END), 0), 2) AS CSAT_SCORE_PCT
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) >= DATE_TRUNC('MONTH', CURRENT_DATE() - INTERVAL '6 MONTHS')
GROUP BY DATE_TRUNC('MONTH', TICKET_CREATION_TIME)
ORDER BY MONTH DESC;

-- =====================================================
-- 2. CSAT BY TEAM/CATEGORY
-- =====================================================
SELECT
  TEAM_NAME,
  COUNT(*) AS TOTAL_TICKETS,
  SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS RATED_TICKETS,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END), 0), 2) AS CSAT_SCORE_PCT,
  COUNT(DISTINCT CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN TICKET_ID END) AS SATISFIED_TICKETS,
  COUNT(DISTINCT CASE WHEN SATISFACTION_RATING_SCORE IN ('unsatisfied', '1', '2') THEN TICKET_ID END) AS UNSATISFIED_TICKETS
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) = DATE_TRUNC('MONTH', CURRENT_DATE())
  AND TEAM_NAME IS NOT NULL
GROUP BY TEAM_NAME
ORDER BY CSAT_SCORE_PCT DESC;

-- =====================================================
-- 3. CSAT TRENDS OVER TIME (Last 6 Months)
-- =====================================================
SELECT
  DATE_TRUNC('WEEK', TICKET_CREATION_TIME) AS WEEK,
  COUNT(*) AS TOTAL_TICKETS,
  SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS RATED_TICKETS,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END), 0), 2) AS CSAT_SCORE_PCT
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) >= DATE_TRUNC('MONTH', CURRENT_DATE() - INTERVAL '6 MONTHS')
GROUP BY DATE_TRUNC('WEEK', TICKET_CREATION_TIME)
ORDER BY WEEK DESC;

-- =====================================================
-- 4. CSAT BY AGENT/ASSIGNEE
-- =====================================================
SELECT
  ASSIGNEE_NAME,
  COUNT(*) AS TOTAL_TICKETS,
  SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) AS RATED_TICKETS,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS RESPONSE_RATE_PCT,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END), 0), 2) AS CSAT_SCORE_PCT,
  COUNT(DISTINCT CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN TICKET_ID END) AS SATISFIED_TICKETS
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) = DATE_TRUNC('MONTH', CURRENT_DATE())
  AND ASSIGNEE_NAME IS NOT NULL
GROUP BY ASSIGNEE_NAME
HAVING COUNT(*) >= 5
ORDER BY CSAT_SCORE_PCT DESC;

-- =====================================================
-- 5. CSAT RATING DISTRIBUTION (Current Month)
-- =====================================================
SELECT
  SATISFACTION_RATING_SCORE,
  COUNT(*) AS COUNT,
  ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) = DATE_TRUNC('MONTH', CURRENT_DATE())
  AND SATISFACTION_RATING_SCORE IS NOT NULL
GROUP BY SATISFACTION_RATING_SCORE
ORDER BY COUNT DESC;

-- =====================================================
-- 6. CSAT vs TTR CORRELATION (By Team)
-- =====================================================
SELECT
  TEAM_NAME,
  COUNT(*) AS TOTAL_TICKETS,
  ROUND(AVG(RESOLVED_TIME_BUSINESS_MINS), 2) AS AVG_TTR_MINS,
  ROUND(100.0 * SUM(CASE WHEN SATISFACTION_RATING_SCORE IN ('satisfied', '5', '4') THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN SATISFACTION_RATING_SCORE IS NOT NULL THEN 1 ELSE 0 END), 0), 2) AS CSAT_SCORE_PCT
FROM SANDBOX_LAKEHOUSE.INTERNAL_ANALYTICS.ZENDESK_PRODUCTIVITY_METRICS_TICKETS
WHERE DATE_TRUNC('MONTH', TICKET_CREATION_TIME) = DATE_TRUNC('MONTH', CURRENT_DATE())
  AND TEAM_NAME IS NOT NULL
GROUP BY TEAM_NAME
ORDER BY CSAT_SCORE_PCT DESC;